### ISSUE TITLE
Provide/install libpqxx to docker

### ISSUE THREAD

**Issue by cppcooper** [BCCF-UBCO-AD/Orthanc-TMI#47]
So one of our hurdles is getting libpqxx installed into the orthanc docker server so that the plugin can access the shared object it will be linked against.

**Comment by brianzhouzc** [comment]
> Perhaps, we could mount the `extern/libpqxx` directory into the docker.. then run cmake/build/install from inside the docker.. by mounting we'd cache the process and hopefully be able to avoid building more than once.. and ideally without breaking the project's build with the intermediate files inside `extern/libpqxx/cmake-build-or-whatever`.
> 
> @brianzhouzc what do you think? doable? acceptable?

This has to be done at the image level, not the container level. Otherwise everytime we start the container it'll have to build the library again. 

It is doable, but at this rate we might want to look at other options. We can't really predict what system the client will decide to deploy on and we can't expect them to build the libraries themselves.

**Comment by cppcooper** [comment]
> It is possible. We will have to override the entry point to the container then. You can put everything you want to execute in a bash script, and I can figure out how to configure docker-compose

How long will this take? I'd like to merge #30 before tomorrow, or at least before end of day tomorrow. The tests won't pass without libpqxx.so available though.

**Comment by brianzhouzc** [comment]
This has been done
